02-Aug-2024 18:27:27.121 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
02-Aug-2024 18:27:27.121 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
02-Aug-2024 18:27:27.122 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@750ff7d3')
02-Aug-2024 19:21:58.423 SEVERE [http-nio-8080-exec-39] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [Unable to compile class for JSP: 

An error occurred at line: [41] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
38:                 %>
39:                 
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 


An error occurred at line: [42] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
39:                 
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 


An error occurred at line: [43] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>


An error occurred at line: [44] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>
47:                 


An error occurred at line: [45] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>
47:                 
48:            <% 


An error occurred at line: [49] in the jsp file: [/MostrarUsuarios.jsp]
Syntax error, insert "Finally" to complete TryStatement
46:                 </tr>
47:                 
48:            <% 
49:                  }
50: 
51:                 %>
52:         </table>


An error occurred at line: [185] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
Syntax error on token "catch", Identifier expected

An error occurred at line: [187] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [187] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_out cannot be resolved to a variable

An error occurred at line: [188] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [188] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [190] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
response cannot be resolved

An error occurred at line: [191] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [193] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [196] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved to a variable

An error occurred at line: [196] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved

An error occurred at line: [199] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
Syntax error on token "finally", { expected

An error occurred at line: [200] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved to a variable

Stacktrace:] with root cause
	org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [41] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
38:                 %>
39:                 
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 


An error occurred at line: [42] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
39:                 
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 


An error occurred at line: [43] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>


An error occurred at line: [44] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>
47:                 


An error occurred at line: [45] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>
47:                 
48:            <% 


An error occurred at line: [49] in the jsp file: [/MostrarUsuarios.jsp]
Syntax error, insert "Finally" to complete TryStatement
46:                 </tr>
47:                 
48:            <% 
49:                  }
50: 
51:                 %>
52:         </table>


An error occurred at line: [185] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
Syntax error on token "catch", Identifier expected

An error occurred at line: [187] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [187] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_out cannot be resolved to a variable

An error occurred at line: [188] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [188] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [190] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
response cannot be resolved

An error occurred at line: [191] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [193] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [196] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved to a variable

An error occurred at line: [196] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved

An error occurred at line: [199] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
Syntax error on token "finally", { expected

An error occurred at line: [200] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved to a variable

Stacktrace:
		at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:81)
		at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:214)
		at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:561)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:398)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:368)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:352)
		at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:603)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:26:16.205 SEVERE [http-nio-8080-exec-46] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [Unable to compile class for JSP: 

An error occurred at line: [41] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
38:                 %>
39:                 
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 


An error occurred at line: [42] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
39:                 
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 


An error occurred at line: [43] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>


An error occurred at line: [44] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>
47:                 


An error occurred at line: [45] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>
47:                 
48:            <% 


An error occurred at line: [49] in the jsp file: [/MostrarUsuarios.jsp]
Syntax error, insert "Finally" to complete TryStatement
46:                 </tr>
47:                 
48:            <% 
49:                  }
50: 
51:                 %>
52:         </table>


An error occurred at line: [185] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
Syntax error on token "catch", Identifier expected

An error occurred at line: [187] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [187] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_out cannot be resolved to a variable

An error occurred at line: [188] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [188] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [190] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
response cannot be resolved

An error occurred at line: [191] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [193] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [196] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved to a variable

An error occurred at line: [196] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved

An error occurred at line: [199] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
Syntax error on token "finally", { expected

An error occurred at line: [200] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved to a variable

Stacktrace:] with root cause
	org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [41] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
38:                 %>
39:                 
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 


An error occurred at line: [42] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
39:                 
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 


An error occurred at line: [43] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
40:                 <tr>
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>


An error occurred at line: [44] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
41:                     <td> <%= usuario.getId()%> </td>
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>
47:                 


An error occurred at line: [45] in the jsp file: [/MostrarUsuarios.jsp]
usuario cannot be resolved
42:                     <td> <%= usuario.getNombres()%> </td> 
43:                     <td> <%= usuario.getAppaterno()%> </td> 
44:                     <td> <%= usuario.getApmaterno()%> </td> 
45:                     <td> <%= usuario.getEdad()%> </td> 
46:                 </tr>
47:                 
48:            <% 


An error occurred at line: [49] in the jsp file: [/MostrarUsuarios.jsp]
Syntax error, insert "Finally" to complete TryStatement
46:                 </tr>
47:                 
48:            <% 
49:                  }
50: 
51:                 %>
52:         </table>


An error occurred at line: [185] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
Syntax error on token "catch", Identifier expected

An error occurred at line: [187] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [187] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_out cannot be resolved to a variable

An error occurred at line: [188] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [188] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [190] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
response cannot be resolved

An error occurred at line: [191] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [193] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
out cannot be resolved

An error occurred at line: [196] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved to a variable

An error occurred at line: [196] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved

An error occurred at line: [199] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
Syntax error on token "finally", { expected

An error occurred at line: [200] in the generated java file: [C:\Users\yohn\Desktop\Portafolio\Java\apache-tomcat-9.0.91-windows-x64\apache-tomcat-9.0.91\work\Catalina\localhost\CrudMySQL\org\apache\jsp\MostrarUsuarios_jsp.java]
_jspx_page_context cannot be resolved to a variable

Stacktrace:
		at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:81)
		at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:214)
		at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:561)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:398)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:368)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:352)
		at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:603)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:26:16.812 SEVERE [http-nio-8080-exec-47] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [org.apache.jasper.JasperException: java.lang.ClassNotFoundException: org.apache.jsp.MostrarUsuarios_jsp] with root cause
	java.lang.ClassNotFoundException: org.apache.jsp.MostrarUsuarios_jsp
		at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
		at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:129)
		at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:58)
		at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150)
		at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:192)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:413)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:26:58.719 SEVERE [http-nio-8080-exec-46] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:30:34.388 SEVERE [http-nio-8080-exec-63] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:30:34.964 SEVERE [http-nio-8080-exec-61] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:30:35.186 SEVERE [http-nio-8080-exec-59] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:30:35.443 SEVERE [http-nio-8080-exec-56] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:30:35.653 SEVERE [http-nio-8080-exec-58] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:30:36.204 SEVERE [http-nio-8080-exec-55] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:30:36.722 SEVERE [http-nio-8080-exec-60] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:30:37.148 SEVERE [http-nio-8080-exec-64] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:30:46.457 SEVERE [http-nio-8080-exec-65] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:30:47.092 SEVERE [http-nio-8080-exec-62] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 19:30:47.339 SEVERE [http-nio-8080-exec-66] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/CrudMySQL] threw exception [An exception occurred processing [/MostrarUsuarios.jsp] at line [34]

31:                   List<EntidadUsuario> usuarios = (List<EntidadUsuario>) request.getAttribute("ListaUsuarios");
32:                    
33: 
34:                   for (EntidadUsuario usuario:usuarios) {
35:                                                                                        
36:                       
37: 


Stacktrace:] with root cause
	java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "usuarios" is null
		at org.apache.jsp.MostrarUsuarios_jsp._jspService(MostrarUsuarios_jsp.java:150)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 20:01:47.226 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
02-Aug-2024 20:01:47.226 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
02-Aug-2024 20:08:19.260 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
02-Aug-2024 20:08:19.260 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
02-Aug-2024 20:08:19.262 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@7c8d5312')
02-Aug-2024 20:10:33.711 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
02-Aug-2024 20:10:33.711 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
02-Aug-2024 20:16:48.622 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
02-Aug-2024 20:16:48.622 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
02-Aug-2024 20:16:48.626 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@1d5d5621')
02-Aug-2024 20:32:49.688 SEVERE [http-nio-8080-exec-91] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [ServletUsuario] in context with path [/CrudMySQL] threw exception
	java.lang.NumberFormatException: For input string: ""
		at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
		at java.base/java.lang.Integer.parseInt(Integer.java:565)
		at java.base/java.lang.Integer.parseInt(Integer.java:685)
		at com.mycompany.crudmysql.ServletUsuario.GuardarUsuarios(ServletUsuario.java:83)
		at com.mycompany.crudmysql.ServletUsuario.doPost(ServletUsuario.java:65)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 21:55:33.162 SEVERE [http-nio-8080-exec-271] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [ServletUsuario] in context with path [/CrudMySQL] threw exception
	java.lang.NumberFormatException: For input string: ""
		at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
		at java.base/java.lang.Integer.parseInt(Integer.java:565)
		at java.base/java.lang.Integer.parseInt(Integer.java:685)
		at com.mycompany.crudmysql.ServletUsuario.EliminarUsuarios(ServletUsuario.java:183)
		at com.mycompany.crudmysql.ServletUsuario.doPost(ServletUsuario.java:81)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1570)
02-Aug-2024 21:55:56.227 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
02-Aug-2024 21:55:56.227 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
